const baseTextStyle = {
  fontFamily: 'Inter',
  fontStyle: 'normal',
}

export const textStyles = {
  'display-1': {
    ...baseTextStyle,
    fontWeight: 'bold',
    fontSize: '64px',
    lineHeight: '72px',
    letterSpacing: '-0.022em',
  },
  'display-2': {
    ...baseTextStyle,
    fontWeight: 600,
    fontSize: '40px',
    lineHeight: '48px',
    letterSpacing: '-0.022em',
    fontFeatureSettings: "'zero' on",
  },
  h1: {
    ...baseTextStyle,
    fontWeight: 600,
    fontSize: '32px',
    lineHeight: '40px',
    letterSpacing: '-0.017em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'zero' on, 'cv05' on",
  },
  'h1-mobile': {
    ...baseTextStyle,
    fontWeight: 300,
    fontSize: '32px',
    lineHeight: '40px',
    letterSpacing: '-0.017em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'zero' on, 'cv05' on",
  },
  h2: {
    ...baseTextStyle,
    fontWeight: 600,
    fontSize: '24px',
    lineHeight: '32px',
    letterSpacing: '-0.019em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  'h2-mobile': {
    ...baseTextStyle,
    fontWeight: 300,
    fontSize: '24px',
    lineHeight: '32px',
    letterSpacing: '-0.019em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  h3: {
    ...baseTextStyle,
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: '32px',
    letterSpacing: '-0.019em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'zero' on, 'cv05' on",
  },
  h4: {
    ...baseTextStyle,
    fontWeight: 500,
    fontSize: '18px',
    lineHeight: '24px',
    letterSpacing: '-0.014em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  'subhead-1': {
    ...baseTextStyle,
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '-0.011em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  'subhead-2': {
    ...baseTextStyle,
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '24px',
    letterSpacing: '-0.006em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'zero' on, 'cv05' on",
  },
  'subhead-3': {
    ...baseTextStyle,
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: '24px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'zero' on, 'cv05' on",
  },
  'body-1': {
    ...baseTextStyle,
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '-0.011em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on, 'cv02' on",
  },
  'body-2': {
    ...baseTextStyle,
    fontWeight: 'normal',
    fontSize: '14px',
    lineHeight: '24px',
    letterSpacing: '-0.006em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  'caption-1': {
    ...baseTextStyle,
    fontWeight: 'medium',
    fontSize: '12px',
    lineHeight: '16px',
    fontFeatureSettings: "'tnum' on, 'cv05' on",
  },
  'caption-2': {
    ...baseTextStyle,
    fontWeight: 'normal',
    fontSize: '12px',
    lineHeight: '16px',
    fontFeatureSettings: "'tnum' on, 'cv05' on",
  },
  link: {
    ...baseTextStyle,
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '-0.011em',
    textDecorationLine: 'underline',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'zero' on, 'cv05' on",
  },
  Legal: {
    ...baseTextStyle,
    fontWeight: 'normal',
    fontSize: '10px',
    lineHeight: '12px',
    fontFeatureSettings: "'tnum' on, 'cv05' on",
  },
  logo: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '24px',
    lineHeight: '32px',
    letterSpacing: '-0.014em',
  },
}
